/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScionPdfRouteRouteImport } from './routes/scion-pdf/route'
import { Route as ScionRouteRouteImport } from './routes/scion/route'
import { Route as DarkswornPdfRouteRouteImport } from './routes/darksworn-pdf/route'
import { Route as IndexRouteImport } from './routes/index'

const ScionPdfRouteRoute = ScionPdfRouteRouteImport.update({
  id: '/scion-pdf',
  path: '/scion-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ScionRouteRoute = ScionRouteRouteImport.update({
  id: '/scion',
  path: '/scion',
  getParentRoute: () => rootRouteImport,
} as any)
const DarkswornPdfRouteRoute = DarkswornPdfRouteRouteImport.update({
  id: '/darksworn-pdf',
  path: '/darksworn-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/darksworn-pdf': typeof DarkswornPdfRouteRoute
  '/scion': typeof ScionRouteRoute
  '/scion-pdf': typeof ScionPdfRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/darksworn-pdf': typeof DarkswornPdfRouteRoute
  '/scion': typeof ScionRouteRoute
  '/scion-pdf': typeof ScionPdfRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/darksworn-pdf': typeof DarkswornPdfRouteRoute
  '/scion': typeof ScionRouteRoute
  '/scion-pdf': typeof ScionPdfRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/darksworn-pdf' | '/scion' | '/scion-pdf'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/darksworn-pdf' | '/scion' | '/scion-pdf'
  id: '__root__' | '/' | '/darksworn-pdf' | '/scion' | '/scion-pdf'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DarkswornPdfRouteRoute: typeof DarkswornPdfRouteRoute
  ScionRouteRoute: typeof ScionRouteRoute
  ScionPdfRouteRoute: typeof ScionPdfRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scion-pdf': {
      id: '/scion-pdf'
      path: '/scion-pdf'
      fullPath: '/scion-pdf'
      preLoaderRoute: typeof ScionPdfRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scion': {
      id: '/scion'
      path: '/scion'
      fullPath: '/scion'
      preLoaderRoute: typeof ScionRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/darksworn-pdf': {
      id: '/darksworn-pdf'
      path: '/darksworn-pdf'
      fullPath: '/darksworn-pdf'
      preLoaderRoute: typeof DarkswornPdfRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DarkswornPdfRouteRoute: DarkswornPdfRouteRoute,
  ScionRouteRoute: ScionRouteRoute,
  ScionPdfRouteRoute: ScionPdfRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
