/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShadowUnseenRouteRouteImport } from './routes/shadow-unseen/route'
import { Route as ScionPdfRouteRouteImport } from './routes/scion-pdf/route'
import { Route as ScionFullPdfRouteRouteImport } from './routes/scion-full-pdf/route'
import { Route as ScionRouteRouteImport } from './routes/scion/route'
import { Route as DarkswornPdfRouteRouteImport } from './routes/darksworn-pdf/route'
import { Route as ConduitUntetheredRouteRouteImport } from './routes/conduit-untethered/route'
import { Route as IndexRouteImport } from './routes/index'

const ShadowUnseenRouteRoute = ShadowUnseenRouteRouteImport.update({
  id: '/shadow-unseen',
  path: '/shadow-unseen',
  getParentRoute: () => rootRouteImport,
} as any)
const ScionPdfRouteRoute = ScionPdfRouteRouteImport.update({
  id: '/scion-pdf',
  path: '/scion-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ScionFullPdfRouteRoute = ScionFullPdfRouteRouteImport.update({
  id: '/scion-full-pdf',
  path: '/scion-full-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ScionRouteRoute = ScionRouteRouteImport.update({
  id: '/scion',
  path: '/scion',
  getParentRoute: () => rootRouteImport,
} as any)
const DarkswornPdfRouteRoute = DarkswornPdfRouteRouteImport.update({
  id: '/darksworn-pdf',
  path: '/darksworn-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ConduitUntetheredRouteRoute = ConduitUntetheredRouteRouteImport.update({
  id: '/conduit-untethered',
  path: '/conduit-untethered',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/conduit-untethered': typeof ConduitUntetheredRouteRoute
  '/darksworn-pdf': typeof DarkswornPdfRouteRoute
  '/scion': typeof ScionRouteRoute
  '/scion-full-pdf': typeof ScionFullPdfRouteRoute
  '/scion-pdf': typeof ScionPdfRouteRoute
  '/shadow-unseen': typeof ShadowUnseenRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/conduit-untethered': typeof ConduitUntetheredRouteRoute
  '/darksworn-pdf': typeof DarkswornPdfRouteRoute
  '/scion': typeof ScionRouteRoute
  '/scion-full-pdf': typeof ScionFullPdfRouteRoute
  '/scion-pdf': typeof ScionPdfRouteRoute
  '/shadow-unseen': typeof ShadowUnseenRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/conduit-untethered': typeof ConduitUntetheredRouteRoute
  '/darksworn-pdf': typeof DarkswornPdfRouteRoute
  '/scion': typeof ScionRouteRoute
  '/scion-full-pdf': typeof ScionFullPdfRouteRoute
  '/scion-pdf': typeof ScionPdfRouteRoute
  '/shadow-unseen': typeof ShadowUnseenRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/conduit-untethered'
    | '/darksworn-pdf'
    | '/scion'
    | '/scion-full-pdf'
    | '/scion-pdf'
    | '/shadow-unseen'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/conduit-untethered'
    | '/darksworn-pdf'
    | '/scion'
    | '/scion-full-pdf'
    | '/scion-pdf'
    | '/shadow-unseen'
  id:
    | '__root__'
    | '/'
    | '/conduit-untethered'
    | '/darksworn-pdf'
    | '/scion'
    | '/scion-full-pdf'
    | '/scion-pdf'
    | '/shadow-unseen'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConduitUntetheredRouteRoute: typeof ConduitUntetheredRouteRoute
  DarkswornPdfRouteRoute: typeof DarkswornPdfRouteRoute
  ScionRouteRoute: typeof ScionRouteRoute
  ScionFullPdfRouteRoute: typeof ScionFullPdfRouteRoute
  ScionPdfRouteRoute: typeof ScionPdfRouteRoute
  ShadowUnseenRouteRoute: typeof ShadowUnseenRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shadow-unseen': {
      id: '/shadow-unseen'
      path: '/shadow-unseen'
      fullPath: '/shadow-unseen'
      preLoaderRoute: typeof ShadowUnseenRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scion-pdf': {
      id: '/scion-pdf'
      path: '/scion-pdf'
      fullPath: '/scion-pdf'
      preLoaderRoute: typeof ScionPdfRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scion-full-pdf': {
      id: '/scion-full-pdf'
      path: '/scion-full-pdf'
      fullPath: '/scion-full-pdf'
      preLoaderRoute: typeof ScionFullPdfRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scion': {
      id: '/scion'
      path: '/scion'
      fullPath: '/scion'
      preLoaderRoute: typeof ScionRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/darksworn-pdf': {
      id: '/darksworn-pdf'
      path: '/darksworn-pdf'
      fullPath: '/darksworn-pdf'
      preLoaderRoute: typeof DarkswornPdfRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conduit-untethered': {
      id: '/conduit-untethered'
      path: '/conduit-untethered'
      fullPath: '/conduit-untethered'
      preLoaderRoute: typeof ConduitUntetheredRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConduitUntetheredRouteRoute: ConduitUntetheredRouteRoute,
  DarkswornPdfRouteRoute: DarkswornPdfRouteRoute,
  ScionRouteRoute: ScionRouteRoute,
  ScionFullPdfRouteRoute: ScionFullPdfRouteRoute,
  ScionPdfRouteRoute: ScionPdfRouteRoute,
  ShadowUnseenRouteRoute: ShadowUnseenRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
